### ISSUE TITLE
[Icon Request] Flappy Bird

### ISSUE THREAD

**Issue by ghost** [Delta-Icons/android#345] opened 2021-12-12 23:38 UTC
Manufacturer : samsung
Model : SM-A125U1
Product : a12uue
Screen Resolution : 720 x 1465 pixels
Android Version : 11
App Version : 1.6.4
CandyBar Version : 3.13.3

Flappy Bird
com.dotgears.flappybird/com.dotgears.flappy.SplashScreen
https://play.google.com/store/apps/details?id=com.dotgears.flappybird   

[icon_request_12_12_2021_17_28_36.zip](https://github.com/Delta-Icons/android/files/7700088/icon_request_12_12_2021_17_28_36.zip)

**Comment by wokija** [comment] 2021-12-13 06:42
Please use the icon request tool inside the app.

Thank you.

**Comment by ColaWagon** [comment] 2021-12-13 16:03
> Please use the icon request tool inside the app.
> 
> Thank you 

Well when i hit send i get "Choose the app you want to use to send the icon request" and i dont know what to do from ther.  

![Uploading Screenshot_20211213-095034_Delta.png…]()

**Comment by wokija** [comment] 2021-12-13 16:16
I can't see the image, but if no app suggestions shows up, that means you've already requested all unthemed applications installed on your phone.

**Comment by creepertron95** [comment] 2021-12-13 17:41
> I can't see the image, but if no app suggestions shows up, that means you've already requested all unthemed applications installed on your phone.

Actually, there is a glitch in CandyBar`s Icon Request where one icon won't show up. You can notice it however when you tap the square button in the corner.

![Screenshot_20211213-113958_Delta](https://user-images.githubusercontent.com/53346722/145861652-4abd9b42-fb09-4b13-a43d-15174b44b564.jpg)

**Comment by wokija** [comment] 2021-12-13 19:26
We'll have to contact Sarsa from CandyBar about this then

**Comment by Donnnno** [comment] 2021-12-14 01:40
Can confirm that this issue is in arcticons too.

**Comment by ColaWagon** [comment] 2021-12-14 08:12
![Screenshot_20211214-021016_Delta](https://user-images.githubusercontent.com/96027970/145958708-463b392b-462d-4158-bb68-d67e279db61f.png)
Here is the img

**Comment by joelchrono12** [comment] 2021-12-14 13:16
> Can confirm that this issue is in arcticons too.

Nice plug :P

But yeah, it is indeed a candy bar problem

**Comment by wokija** [comment] 2021-12-14 16:50
> ![Screenshot_20211214-021016_Delta](https://user-images.githubusercontent.com/96027970/145958708-463b392b-462d-4158-bb68-d67e279db61f.png) Here is the img

This is weird. Normally you would get an empty checkbox at the right of the unthemed icon. And I can guess nothing happen if you press on any of those, right?

**Comment by ColaWagon** [comment] 2021-12-18 09:34
It lets me pick more then one and then send
![Screenshot_20211218-033056_Delta](https://user-images.githubusercontent.com/96027970/146636458-a976e051-5710-4af3-b829-f2053e82872f.png)

**Comment by moertel** [comment] 2022-03-20 19:08
@wokija @creepertron95 FYI I was able to reproduce the problem in CandyBar Dev. It happens only for apps that have Premium Requests disabled. (If you enable it the problem immediately disappears.) I wasn't able to find out _why_ it happens yet but we're one step closer. https://github.com/zixpo/candybar/issues/66#issuecomment-1073312595

**Comment by leifniem** [comment] 2022-04-04 18:45
Closing this since it is out of our scope to solve.

**Closed by leifniem** 2022-04-04 18:45 UTC
