### ISSUE TITLE
can't pick custom icon in lawnchair

### ISSUE THREAD

**Issue by mintyleaf** [Delta-Icons/android#368] opened 2022-02-08 22:39 UTC
using last lawnchair 12 (#649 build, for example), with three dot menu -> experimental features -> per app icon customisation enabled, when I try to pick icon from Delta icon pack - there is no categories and icons at all, also when I press "open external picker" - Delta app just opens and I can't somehow send back to caller activity picked icon from there

I downloaded candy icons pack for testing - there I can pick icons
also I can pick system icons
so, I guess, there is some lack of up to date integration with icon picking thing in launcher

**Comment by SqrHornet** [comment] 2022-02-13 14:24
Also can confirm. Doesn't happen with other icons pack (I checked viral icon pack)

**Comment by AbsurdUsername** [comment] 2022-02-13 16:09
Uhm I tested with another icon pack and it's working. I don't think it's candybar or lawnchair either. Maybe @Donnnno can give us an insight on what's happening since his icon pack it's working as shown above and built with candybar?

**Comment by Donnnno** [comment] 2022-02-13 16:11
Good question! I don't know exactly...

Is the dashboard up to date with the candybar repo?

**Comment by AbsurdUsername** [comment] 2022-02-13 16:36
Seems like it 
https://github.com/Delta-Icons/android/blob/957bae3ce27e177040c19081f336fe7a973d967f/app/build.gradle#L67-L81

**Comment by creepertron95** [comment] 2022-02-13 17:11
> Also can confirm. Doesn't happen with other icons pack (I checked viral icon pack)

Might be off topic but, is this the latest Viral update that now uses a new ([Blueprint](https://github.com/jahirfiquitiva/Blueprint)) icon dashboard instead of the CandyBar one?

**Comment by Donnnno** [comment] 2022-02-13 17:56
Arcticons uses a modified candybar dashboard, and it still works :$

**Comment by AbsurdUsername** [comment] 2022-02-13 22:19
Ok quick question: @mintyleaf , @SqrHornet do you use QuickSwitch magisk module?

Because I run the app on android studio clean project and lawnchair and everything is working, with no magisk installed.

**Comment by SqrHornet** [comment] 2022-02-13 22:38
Actually I do, I didn't know quickswitch might have had something to do with it in the first place. Still other icon packs manage to work 🤔

**Comment by AbsurdUsername** [comment] 2022-02-13 22:50
Thanks for the quick reply. I tested really quickly on my phone by uninstalling quickswitch and trying but still no result.
I'm kinda at loss here because dependencies are correct, a fresh install on android studio emulator works fine, quickswitch is not the problem and I'm back to zero.
Is it Delta? Candybar? Lawnchair?
I know he doesn't have much time but I'd like to summon @leifniem.

**Comment by leifniem** [comment] 2022-02-13 23:40
Thanks for tagging me @AbsurdUsername - if we're using the latest candybar (@wokija probably knows better than me) my only guesses would be a category name causing an error, our additional manual naming of the drawables or a broken drawable causing this.

@mintyleaf have you tried making a logcat yet? Since lawnchair is using debug builds by default iirc the output should be very detailed.

**Comment by wokija** [comment] 2022-02-14 04:52
We indeed use latest candybar version. I could try building an apk without the name attribute and see if that solves the issue. If so, we could just scrap the idea of using custom name for the sake of functionality.

**Comment by Donnnno** [comment] 2022-02-14 11:30
Can confirm, this works for me with delta too!

**Comment by AbsurdUsername** [comment] 2022-02-14 12:29
Logcat doesn't show much the only worthy thing i saw was this

_18728 20309 E ite.leifs.delt: Invalid ID 0x00000000.
18728 20309 E GlideExecutor: Request threw uncaught throwable
18728 20309 E GlideExecutor: android.content.res.Resources$NotFoundException: Resource ID #0x0
18728 20309 E GlideExecutor:         at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
18728 20309 E GlideExecutor:         at android.content.res.Resources.getDrawableForDensity(Resources.java:982)
18728 20309 E GlideExecutor:         at android.content.res.Resources.getDrawable(Resources.java:922)
18728 20309 E GlideExecutor:         at android.content.Context.getDrawable(Context.java:693)
18728 20309 E GlideExecutor:         at w.a.d(SourceFile:2)
18728 20309 E GlideExecutor:         at candybar.lib.utils.a.e(SourceFile:3)
18728 20309 E GlideExecutor:         at candybar.lib.utils.a.c(SourceFile:2)
18728 20309 E GlideExecutor:         at q2.z.j(SourceFile:3)
18728 20309 E GlideExecutor:         at q2.z.b(SourceFile:12)
18728 20309 E GlideExecutor:         at q2.h.y(SourceFile:4)
18728 20309 E GlideExecutor:         at q2.h.A(SourceFile:7)
18728 20309 E GlideExecutor:         at q2.h.run(SourceFile:7)
18728 20309 E GlideExecutor:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
18728 20309 E GlideExecutor:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
18728 20309 E GlideExecutor:         at java.lang.Thread.run(Thread.java:923)
18728 20309 E GlideExecutor:         at t2.a$b$a.run(SourceFile:6)
18728 18728 E Delta   : Failed to query purchases. Response Code: -1
18728 18728 W Glide   : Load failed for drawable://0 with size [720x720]
18728 18728 W Glide   : class q2.q: Failed to load resource
18728 18728 W Glide   : There was 1 cause:
18728 18728 W Glide   : android.content.res.Resources$NotFoundException(Resource ID #0x0)
18728 18728 W Glide   :  call GlideException#logRootCauses(String) for more detail
18728 18728 W Glide   :   Cause (1 of 1): class android.content.res.Resources$NotFoundException: Resource ID #0x0
18728 18728 I Glide   : Root cause (1 of 1)
18728 18728 I Glide   : android.content.res.Resources$NotFoundException: Resource ID #0x0
18728 18728 I Glide   :      at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
18728 18728 I Glide   :      at android.content.res.Resources.getDrawableForDensity(Resources.java:982)
18728 18728 I Glide   :      at android.content.res.Resources.getDrawable(Resources.java:922)
18728 18728 I Glide   :      at android.content.Context.getDrawable(Context.java:693)
18728 18728 I Glide   :      at w.a.d(SourceFile:2)
18728 18728 I Glide   :      at candybar.lib.utils.a.e(SourceFile:3)
18728 18728 I Glide   :      at candybar.lib.utils.a.c(SourceFile:2)
18728 18728 I Glide   :      at q2.z.j(SourceFile:3)
18728 18728 I Glide   :      at q2.z.b(SourceFile:12)
18728 18728 I Glide   :      at q2.h.y(SourceFile:4)
18728 18728 I Glide   :      at q2.h.A(SourceFile:7)
18728 18728 I Glide   :      at q2.h.run(SourceFile:7)
18728 18728 I Glide   :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
18728 18728 I Glide   :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
18728 18728 I Glide   :      at java.lang.Thread.run(Thread.java:923)
18728 18728 I Glide   :      at t2.a$b$a.run(SourceFile:6)_

I can't make much of this maybe someone understand better.
I'm afraid is more a rom/phone issue

**Comment by leifniem** [comment] 2022-02-14 14:02
@AbsurdUsername have you tried it with the newest beta?

The logcat shows some resources missing, which I guess to be broken drawables, but since it works for other people it might be a specific lawnchair version that is prone to this bug.

**Comment by AbsurdUsername** [comment] 2022-02-14 14:15
> @AbsurdUsername have you tried it with the newest beta?
> 
> The logcat shows some resources missing, which I guess to be broken drawables, but since it works for other people it might be a specific lawnchair version that is prone to this bug.

You are correct with the newest beta it's working!

**Comment by SqrHornet** [comment] 2022-02-14 18:48
@AbsurdUsername The icons do show after updating to newest beta. But there is another bug on my end and I'm not sure which app is to blame. Icon categories end with letter O. Also it's not possible to find any icon starting with P or any next letter via search bar. If you could verify if it also happens in your case.
![Screenshot_20220214-194229_Lawnchair](https://user-images.githubusercontent.com/84623999/153926692-939e50d2-d52e-403a-93a5-0ab1cde09cf6.png)

**Comment by mintyleaf** [comment] 2022-02-14 22:05
hey, sorry for misreading this)
how can I get latest beta?
I'm already beta tester in play store, but there is no update yet =\ (maybe I'm blind and I gotta go check this repo after commenting)
btw if logs still needed I easily can grab them tomorrow

**Comment by AbsurdUsername** [comment] 2022-02-14 23:04
> hey, sorry for misreading this) how can I get latest beta? I'm already beta tester in play store, but there is no update yet =\ (maybe I'm blind and I gotta go check this repo after commenting) btw if logs still needed I easily can grab them tomorrow

All good, you can get it [here](https://github.com/Delta-Icons/android/releases)

**Comment by wokija** [comment] 2022-02-15 05:39
> @SqrHornet you're right same on my end. Could you verify please? @wokija

Same on my device. That's strange

**Comment by mintyleaf** [comment] 2022-02-15 06:46
> > hey, sorry for misreading this) how can I get latest beta? I'm already beta tester in play store, but there is no update yet =\ (maybe I'm blind and I gotta go check this repo after commenting) btw if logs still needed I easily can grab them tomorrow
> 
> All good, you can get it [here](https://github.com/Delta-Icons/android/releases)

it's working)

**Comment by AbsurdUsername** [comment] 2022-02-15 14:02
> > @SqrHornet you're right same on my end. Could you verify please? @wokija
> 
> Same on my device. That's strange

Logcat shows nothing.
At this point I suggest to release the update and wait for further lawnchair updates to see if anything changes and leave this open. @leifniem @wokija

**Comment by leifniem** [comment] 2022-04-04 18:42
I recently tested it with Lawnchair 12A5 and it seemed to work no problem at all, did anyone face any further issues?

**Comment by wokija** [comment] 2022-04-04 19:09
> Same. but found the error in the drawables:

Not part of current release. I messed up the last conflicts correction :roll_eyes:

**Comment by leifniem** [comment] 2022-05-29 22:09
This seems fixed in 12.1.0 Alpha 3. Can anyone confirm it is for them too?

**Comment by AbsurdUsername** [comment] 2022-05-29 22:14
Yep can confirm, fixed

**Closed** 2022-05-29 23:06 UTC
